language: cpp
sudo: required
dist: bionic
os:
  - linux
  - osx
compiler:
  - gcc
before_install:
  - source setup.sh
install:
  - pip install -e .
  - pip install -r requirements-dev.txt
script:
  - ./run_mypy.sh
  - ./run_tests.sh
  - black --check .
  - black --diff .
