from typing import Any

class DuplicatedNameError(NameError): ...

class NameScope:
    def __init__(self) -> None: ...
    def is_used(self, name: Any): ...
    def register(self, name: Any, deduplicate: bool = ...): ...
    def deduplicate(self, name: Any): ...
    def get_child(self): ...

class _StrCaching: ...

class _StringReferenceCaching:
    def get_reference(self): ...

class _HasMetadata:
    def set_metadata(self, name: Any, node: Any) -> None: ...
