from . import ffi as ffi
from typing import Any

def create_context(): ...
def get_global_context(): ...

class ContextRef(ffi.ObjectRef):
    def __init__(self, context_ptr: Any) -> None: ...

class GlobalContextRef(ContextRef): ...
