from . import ffi as ffi
from typing import Any

def initialize() -> None: ...
def initialize_all_targets() -> None: ...
def initialize_all_asmprinters() -> None: ...
def initialize_native_target() -> None: ...
def initialize_native_asmprinter() -> None: ...
def initialize_native_asmparser() -> None: ...
def shutdown() -> None: ...

llvm_version_info: Any
